version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.9.0.397

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      # Run just to install deps.
      - run: "clojure -A:test -e ''"

      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: v2-dependencies-{{ checksum "deps.edn" }}

      # run tests!
      - run: mkdir -p test-results/kaocha
      - run: bin/kaocha --plugin kaocha.plugin/junit-xml --junit-xml-file junit.xml --plugin kaocha.plugin/profiling
      - store_test_results:
          path: test-results
