version: 2
jobs:
  build:
    docker:
      - image: clojure/openjdk8-tools-deps-alpine

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Run just to install deps.
      - run: "clojure -e ''"

      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: v1-dependencies-{{ checksum "deps.edn" }}

      # run tests!
      - run: bin/kaocha